// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using Debug = System.Diagnostics.Debug;

namespace michael.iOS
{
	public partial class InitViewController : UIViewController
	{
		public InitViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();



			btnSend.TouchUpInside += (object sender, EventArgs e) => {

				InvokeOnMainThread(
					()=>{

						//lbMessage.Text =@"";

						this.PerformSegue( "moveToMenuViewSegue", this );
					}
				);

			};

		}

		public override void TouchesBegan (Foundation.NSSet touches, UIEvent evt)
		{
			base.TouchesBegan (touches, evt);
			var touch = touches.AnyObject as UITouch;
			Debug.WriteLine ($"TapCount:{touch.TapCount}");

		}
		public override void TouchesMoved (NSSet touches, UIEvent evt)
		{
			base.TouchesMoved (touches, evt);
			var touch = touches.AnyObject as UITouch;
			//var pointOfButton = touch.PreviousLocationInView (this.btnSend);
			var pointOfView = touch.LocationInView (this.View);
			Debug.WriteLine ( $"X:{pointOfView.X}, Y:{pointOfView.Y}"   ); 
		}

		public override void TouchesEnded (Foundation.NSSet touches, UIEvent evt)
		{
			base.TouchesEnded (touches, evt);
			Debug.WriteLine (@"TouchesEnded");
		}


	}
}
