// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace michael.iOS
{
	public partial class TestViewController : UIViewController
	{
		public TestViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
